# Generated by Django 5.1.3 on 2025-08-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='cv',
        ),
        migrations.AddField(
            model_name='application',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='past_work_references',
            field=models.TextField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='project_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='qualifications',
            field=models.TextField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='university',
            field=models.CharField(default=0.0, max_length=200),
            preserve_default=False,
        ),
    ]
