# Generated by Django 5.1.3 on 2025-08-18 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_application_cv_application_gpa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
            preserve_default=False,
        ),
    ]
