# Generated by Django 5.1.3 on 2025-12-11 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_post_image_post_video_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
